package gui;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.SQLException;
import exceptions.CannotGenerateClientException;
import exceptions.ClientAlreadyExistException;
import gui.TextPrompt.Show;
import beans.ClientBean;
import beans.ClientType;
import actions.AdminActions;

public class AddNewClientWindow extends javax.swing.JFrame 
{
	/**
	 * Creates new form AddNewClientWindow
	 */
	public AddNewClientWindow() {
		initComponents();
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		idLabel = new javax.swing.JLabel();
		nameLabel = new javax.swing.JLabel();
		passwordLabel = new javax.swing.JLabel();
		addressLabel = new javax.swing.JLabel();
		emailLabel = new javax.swing.JLabel();
		phoneLabel = new javax.swing.JLabel();
		commentLabel = new javax.swing.JLabel();
		jScrollPane6 = new javax.swing.JScrollPane();
		commentTextArea = new javax.swing.JTextArea();
		addNewClientButton = new javax.swing.JButton();
		firstDepositLabel = new javax.swing.JLabel();
		idTextField = new javax.swing.JTextField();
		nameTextField = new javax.swing.JTextField();
		passwordTextField = new javax.swing.JPasswordField();
		addressTextField = new javax.swing.JTextField();
		emailTextField = new javax.swing.JTextField();
		phoneTextField = new javax.swing.JTextField();
		firstDepositTextField = new javax.swing.JTextField();
		backButton = new javax.swing.JButton();

		TextPrompt promptId = new TextPrompt("<client id>", idTextField, Show.ALWAYS);
		promptId.changeStyle(Font.ITALIC);
		promptId.changeAlpha(0.5f);

		TextPrompt promptName = new TextPrompt("<first name> <last name>", nameTextField, Show.ALWAYS);
		promptName.changeStyle(Font.ITALIC);
		promptName.changeAlpha(0.5f);

		TextPrompt promptPassword = new TextPrompt("<password>", passwordTextField, Show.ALWAYS);
		promptPassword.changeStyle(Font.ITALIC);
		promptPassword.changeAlpha(0.5f);

		TextPrompt promptAddress = new TextPrompt("<street> <house number> <city>", addressTextField, Show.ALWAYS);
		promptAddress.changeStyle(Font.ITALIC);
		promptAddress.changeAlpha(0.5f);

		TextPrompt promptEmail = new TextPrompt("<example@gmail.com>", emailTextField, Show.ALWAYS);
		promptEmail.changeStyle(Font.ITALIC);
		promptEmail.changeAlpha(0.5f);

		TextPrompt promptPhone = new TextPrompt("<phone number>", phoneTextField, Show.ALWAYS);
		promptPhone.changeStyle(Font.ITALIC);
		promptPhone.changeAlpha(0.5f);

		TextPrompt promptFirstDeposit = new TextPrompt("<first deposit in USD>", firstDepositTextField, Show.ALWAYS);
		promptFirstDeposit.changeStyle(Font.ITALIC);
		promptFirstDeposit.changeAlpha(0.5f);

		TextPrompt promptComment = new TextPrompt("<Enter comment>", commentTextArea, Show.ALWAYS);
		promptComment.changeStyle(Font.ITALIC);
		promptComment.changeAlpha(0.5f);

		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

		// Center the frame in the center of the screen
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

		int w = this.getSize().width;
		int h = this.getSize().height;
		int x = (dim.width-w)/3;
		int y = (dim.height-h)/5;
		this.setLocation(x, y);

		idLabel.setText("ID");

		nameLabel.setText("Full name");

		passwordLabel.setText("Password");

		addressLabel.setText("Address");

		emailLabel.setText("Email");

		phoneLabel.setText("Phone");

		commentLabel.setText("Comment");

		commentTextArea.setColumns(20);
		commentTextArea.setRows(5);
		jScrollPane6.setViewportView(commentTextArea);

		addNewClientButton.setText("Add new client");
		addNewClientButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addNewClientButtonActionPerformed(evt);
			}
		});

		firstDepositLabel.setText("First deposit");

		backButton.setText("Back");
		backButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(33, 33, 33)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
										.addComponent(idLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(firstDepositLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(commentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(27, 27, 27)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
														.addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(addressTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
														.addComponent(passwordTextField, javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(idTextField, javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(emailTextField, javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(phoneTextField, javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(firstDepositTextField, javax.swing.GroupLayout.Alignment.LEADING))
														.addGroup(layout.createSequentialGroup()
																.addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18)
																.addComponent(addNewClientButton)))
																.addGap(0, 61, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(47, 47, 47)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(firstDepositLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(firstDepositTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGap(20, 20, 20)
																				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(commentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGap(26, 26, 26)
																						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																								.addComponent(addNewClientButton)
																								.addComponent(backButton))
																								.addGap(28, 28, 28))
				);

		pack();
	}// </editor-fold>                        

	private void addNewClientButtonActionPerformed(java.awt.event.ActionEvent evt) 
	{      
		SuccessMessageWindow successMessageWindow = new SuccessMessageWindow();
		ErrorMessageWindow errorMessageWindow = new ErrorMessageWindow();

		double firstAmount = Double.parseDouble(firstDepositTextField.getText());
		String accountComment = commentTextArea.getText();
		ClientType type = null;
		ClientBean newClient = new ClientBean(Long.parseLong(idTextField.getText()), 
				nameTextField.getText(), 
				passwordTextField.getText(), 
				type, 
				addressTextField.getText(),	
				emailTextField.getText(), 
				Long.parseLong(phoneTextField.getText()), 
				commentTextArea.getText());
		AdminActions adminAction = new AdminActions();
		try 
		{
			adminAction.addNewClient(newClient, firstAmount, accountComment);
			//new window of success
			successMessageWindow.getSuccessLabel().setText("New client and account successfully generated");
			successMessageWindow.setVisible(true);
			this.idTextField.setText("");
			this.nameTextField.setText("");
			this.passwordTextField.setText("");
			this.addressTextField.setText("");
			this.emailTextField.setText("");
			this.phoneTextField.setText("");
			this.firstDepositTextField.setText("");
			this.commentTextArea.setText("");
		} 
		catch (SQLException e) 
		{
			errorMessageWindow.getErrorTextMsg().setText("SQL Error has occurred, please try again");
			errorMessageWindow.setVisible(true);
		} 
		catch (ClientAlreadyExistException e) 
		{
			errorMessageWindow.getErrorTextMsg().setText(e.getMessage());
			errorMessageWindow.setVisible(true);
		} 
		catch (CannotGenerateClientException e) 
		{
			errorMessageWindow.getErrorTextMsg().setText(e.getMessage());
			errorMessageWindow.setVisible(true);
		} 
	}                                                  

	private void backButtonActionPerformed(java.awt.event.ActionEvent evt) 
	{                                           
		this.setVisible(false);
		this.dispose();
	}                                          

	// Variables declaration - do not modify                     
	private javax.swing.JButton addNewClientButton;
	private javax.swing.JLabel addressLabel;
	private javax.swing.JTextField addressTextField;
	private javax.swing.JButton backButton;
	private javax.swing.JLabel commentLabel;
	private javax.swing.JTextArea commentTextArea;
	private javax.swing.JLabel emailLabel;
	private javax.swing.JTextField emailTextField;
	private javax.swing.JLabel firstDepositLabel;
	private javax.swing.JTextField firstDepositTextField;
	private javax.swing.JLabel idLabel;
	private javax.swing.JTextField idTextField;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JLabel nameLabel;
	private javax.swing.JTextField nameTextField;
	private javax.swing.JLabel passwordLabel;
	private javax.swing.JPasswordField passwordTextField;
	private javax.swing.JLabel phoneLabel;
	private javax.swing.JTextField phoneTextField;
	// End of variables declaration      
}                                     

